- name: Clean textpattern dir
  file:
    state: absent
    path: "{{ textpattern_install_dir }}"

- name: Clean textpattern dir
  file:
    state: directory
    path: "{{ textpattern_install_dir }}"

- name: Create temporary dir
  ansible.builtin.tempfile:
    state: directory
  register: tmpdir


- name: Download textpattern
  get_url:
    url: https://github.com/textpattern/textpattern/releases/download/{{ textpattern_version }}/textpattern-{{ textpattern_version }}.tar.gz
    dest: /tmp/textpattern.tgz

- name: Extract textpattern
  ansible.builtin.unarchive:
    remote_src: yes
    src: /tmp/textpattern.tgz
    dest: "{{ tmpdir.path }}"

- name: Move textpattern to final location
  copy: remote_src=True src="{{ tmpdir.path }}/textpattern-{{ textpattern_version }}/" dest="{{ textpattern_install_dir }}"

- name: textpattern config
  template: src=config.php.j2 dest="{{ textpattern_install_dir }}/textpattern/config.php"

- name: Populate database
  uri:
    url: http://192.168.56.51/textpattern/textpattern/setup/index.php
    method: POST
    body_format: form-urlencoded
    body:
      RealName: Sys Admin
      email: admin@acme.org
      name: admin
      pass: admin
      siteurl: http://192.168.56.51/textpattern
      theme: hive
      public_theme: four-point-eight
      Submit: Next
      step: step_createTxp
    status_code: 200

- name: remove tmp files
  file: state=absent path="{{ item }}"
  loop:
    - /tmp/textpattern.tgz
    - "{{ tmpdir.path }}"
